### ISSUE TITLE
[Feature Request] Backport fix for MC-183884 - Shulkers not being able to be next to each other

### ISSUE THREAD

**Issue by pixelplanetdev** [manyrandomthings/minitweaks#11]
In the 21w03a Mojang fixed https://bugs.mojang.com/browse/MC-183884 which now allows shulkers to be next to each other.
This is very handy for shulker farms with minecart pick-up, because when a minecart with a shulker passes by another shulker, it will no longer teleport away.

I think many people who use this mod to backport shulker cloning would really appreciate this.

**Comment by manyrandomthings** [comment]
Fixed in 26af9fc, will be released with the next version (1.0.15), or here's the fixed 1.0.14 version from github actions: https://github.com/manyrandomthings/minitweaks/suites/2635252059/artifacts/57816973
