### ISSUE TITLE
Convenient mobGriefing crash (1.17)

### ISSUE THREAD

**Issue by clmc99** [manyrandomthings/minitweaks#14]
Minecraft crashes on startup with only Convenient mobGriefing, Fabric API, Carpet, and MiniTweaks in the mods folder. Neither Convenient mobGriefing nor Carpet + MiniTweaks crashes by itself. Also created [an issue](https://github.com/A5b84/convenient-mobgriefing/issues/6) in the Convenient mobGriefing GitHub. [latest.log](https://github.com/manyrandomthings/minitweaks/files/6664396/latest.log) (edited to include correct latest.log)

Update: It appears to have something to do with how Convenient mobGriefing implements ender dragon griefing. When I download the Convenient mobGriefing source, remove all mention of ender dragon, and recompile, Minecraft boots normally ([zip](https://github.com/manyrandomthings/minitweaks/files/6665153/convenient-mobgriefing-main.MODIFIED.zip)/[jar](https://drive.google.com/file/d/18or_i7FhZQC0KR_06C2mzOV5UTKa6gET/view?usp=sharing))

**Comment by A5b84** [comment]
Convenient mobGriefing was the issue but it should be fixed now, I think this can be closed :)
