### ISSUE TITLE
Bug: minecarts jump out of tracks with minecartsSpeedMultiplier>=2.1

### ISSUE THREAD

**Issue by MeeniMc** [manyrandomthings/minitweaks#2]
When setting  minecartSpeedMultiplier to say 2.1, minecarts do go faster in straight line, but they jump out of the tracks in turns.  

## How to replicate?

1. Build a 5x5 square with redstone blocks, raised from surrounding terrain.
2. Lay tracks on top (straights with power rails, corners with normal rails)
3. Put down a minecart on the track and jump in it
4. go forward, with higher speed multipliers, your minecart will quickly miss a turn and get out of the tracks.

**Comment by manyrandomthings** [comment]
This is more of a problem with how rails work with vanilla and I don't think it can really be fixed without a rewrite of how rails work. But it can somewhat be mitigated by letting the minecart slow down before turns or having less steep turns

**Comment by MeeniMc** [comment]
Pity, this is an extremely good idea, but as-is, breaks every hopper-minecart collection system.

Maybe an option could be added to have **different speed multipliers for different types of minecarts**; In particular, player-riding minecarts so that one may lay specific track layouts for that use case, but hopper-minecarts would still run normal speed and collection systems would not be damaged.

**Comment by MeeniMc** [comment]
Ok just tried there is no such thing as 'less steep turns', any speed above 16 will have the cart jump out of tracks, even in 'diagonal' turns.

It is possible to prevent the cart jumping off tracks by putting 'wall' blocks around the corner exit. 

Also, speed multipliers above 3.75 appear to have no further effect. Maximum speed is capped at 30m/s in any case. They do however cause minecarts to clip walls in corners and get stuck.

## In summary

### Works:
* Wall encased rails work as intended with max-speed turn at multiplier 3.75. 
* Non-encased rails work as intended with max-speed turn at mutliplier 2.0. 

### Don't work:

* Wall encased rails with speed multiplier >3.75 will have minecart get stuck in turns (even with glass pane walls, didn't try every block depths, but given that the cart doesn't actually travel faster, the interest of running > 3.75 is dubious).
* Non-encased rails with speed multiplier > 2.0 will have minecarts jump out of tracks.




In any case, you should warn in the tooltip that this feature has weird behavior for multipliers greater than 2.0 :)

**Comment by manyrandomthings** [comment]
I added a note to the minecartSpeedMultiplier rule and added minecartSpeedMultiplierPassengersOnly (there's a build on github actions tab) which should fix some of the issues with other minecart types. Other than this nothing else can really be done to fix this because it's an issue with the way vanilla works.
