### ISSUE TITLE
dyeableShearedSheep conflicts with Jello and prevents the game from starting

### ISSUE THREAD

**Issue by SplendidAlakey** [manyrandomthings/minitweaks#22]
**MC** 1.18.2
**MiniTweaks** 1.2.1
**[Jello](https://www.curseforge.com/minecraft/mc-mods/jello)** 3.2.5

Logs: https://gist.github.com/Footage2-Amply-Pounce/ef4a956aa2f0656f53deac694a73d73a

**Comment by manyrandomthings** [comment]
Should be fixed for the 1.19 release but if you need it for 1.18.2 version you can use the github actions build artifacts from here: https://github.com/manyrandomthings/minitweaks/actions/runs/2457000926
