### ISSUE TITLE
Upload to CurseForge?

### ISSUE THREAD

**Issue by RandomGgames** [manyrandomthings/minitweaks#23]
Would it be possible to have this posted to CurseForge? Could I post it for you if you can't for whatever reason?

**Comment by manyrandomthings** [comment]
I just put it on Modrinth now: https://modrinth.com/mod/minitweaks
I don't really want to put it on curseforge though

**Comment by RandomGgames** [comment]
Thank you!
I asked about CurseForge specifically because I made a python script to auto-update mods through their API but modrinth also has one too so I might be able to download latest versions through their api as well *fingers crossed*. If so yay! If not, than I'll just deal, all good.

**Comment by manyrandomthings** [comment]
Now on curseforge: https://www.curseforge.com/minecraft/mc-mods/carpet-minitweaks/
