### ISSUE TITLE
CurseForge release

### ISSUE THREAD

**Issue by clarfonthey** [manyrandomthings/minitweaks#27]
Hi, I figure you didn't want to upload this to CurseForge, but you probably want to clarify in the GH readme that this is a completely different mod, in case people get confused.

http://curseforge.com/minecraft/mc-mods/minitweaks

**Comment by manyrandomthings** [comment]
That mod is only for forge 1.16, and seems likely abandoned, so it's not really that big of a deal, and I already have the only places to download listed in the readme.

**Comment by clarfonthey** [comment]
(For what it's worth, when I initially wrote this I thought that it was hosting a copy of the mod potentially maliciously, and then I found out that I just can't read. So, totally fair.)

**Comment by manyrandomthings** [comment]
Now on curseforge: https://www.curseforge.com/minecraft/mc-mods/carpet-minitweaks/
