### ISSUE TITLE
Crash with "Path under fence gates"

### ISSUE THREAD

**Issue by SplendidAlakey** [manyrandomthings/minitweaks#28]
**MC** 1.19.2
**MiniTweaks** 1.3.2
**[Path under fence gates](https://www.curseforge.com/minecraft/mc-mods/pathunderfencegates/files/3983611)** 1.2.1

The game crashes on startup with both mods installed.

Also reported there: https://github.com/Steveplays28/pathunderfencegates/issues/4

Logs: https://gist.github.com/SplendidAlakey/0b9531408c5616ac5194b8c7fcfc0e51

**Comment by Steveplays28** [comment]
Fixed on my side in [Path Under Fence Gates 1.2.2](https://github.com/Steveplays28/pathunderfencegates/releases/tag/1.2.2).
I've tested it, it doesn't crash on startup anymore, and the snow shaving works as intended.

**Comment by SplendidAlakey** [comment]
Thanks!
