### ISSUE TITLE
Crash on using echo shard on shrieker

### ISSUE THREAD

**Issue by JustACommonGuy** [manyrandomthings/minitweaks#34]
After enabling `echoShardsEnableShriekers`, the game crashes when using an echo shard on a shrieker.

Using the latest version in Minecraft 1.20.6.
[Crash report](https://mclo.gs/9tBR7fu)

It appears that the return value of `onUseWithItem` is expected to be an `ItemActionResult`.

https://github.com/manyrandomthings/minitweaks/blob/f3ef3fcb73e92b511a708459d805fd34d9acfaa5/src/main/java/minitweaks/mixins/block/all/AbstractBlockMixin.java#L20

Changing `ActionResult` to `ItemActionResult` seems to fix the issue.

**Comment by manyrandomthings** [comment]
Fixed in 1.4.4
