### ISSUE TITLE
1.17- 21w03a shulker cloning changes

### ISSUE THREAD

**Issue by rodrigomenes2** [manyrandomthings/minitweaks#5]
The shulker proprietes changed in the new snapshot, now shulkers don't mantain their overworld coordinates  when entering a nether portal. Are you planning to update that in the carpet mini tweakes "shulkerCloning" feature?

**Comment by manyrandomthings** [comment]
I spent a bit of time looking into how to fix this and I don't see any easy way to fix this, so unless someone else knows how to fix this it will probably have to remain until 1.17

**Comment by rodrigomenes2** [comment]
oh, ok. Is it possible to get the shulker cloning in 1.16.3?

**Comment by manyrandomthings** [comment]
I decided to look into this a bit further and found an easy enough fix that should work. shulkerPortalFix is now in 1.0.12
