### ISSUE TITLE
Crash on startup with "Ivan Carpet Addition"

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [manyrandomthings/minitweaks#6]
MiniTweaks crashes on startup with [Ivan Carpet Addition](https://github.com/Ivan-YFw/Ivan-Carpet-Addition) version 1.2.0. It does *not* crash with version 1.1.0. No crash report was generated, but I can provide logs on both versions (of Ivan Carpet Addition):

[(Ivan Carpet Addition) Version 1.1.0 (no crash)](https://gist.github.com/DragonEggBedrockBreaking/23a2d4a6ad8291c9987c5f1e8120fa41)

[(Ivan Carpet Addition) Version 1.2.0 (crash)](https://gist.github.com/DragonEggBedrockBreaking/af71eb4748a8461284c18e26e0e2b184)

**Comment by manyrandomthings** [comment]
Their mod overwrites the CreeperEntity explode method completely (Which is just a really bad way to do mixins):
https://github.com/Ivan-YFw/Ivan-Carpet-Addition/blob/fabric-1.15.2/src/main/java/me/ivan/ivancarpetaddition/mixins/rule/creeperDropCompletely/CreeperEntityMixin.java#L26

While minitweaks just modifies the destructionType argument for world.createExplosion:
https://github.com/manyrandomthings/minitweaks/blob/master/src/main/java/minitweaks/mixins/CreeperEntity_ExplosionGriefMixin.java#L13

I can solve it just by making minitweaks have a higher priority for that mixin, but they should really look into making it not overwrite the method.
Github actions artifacts with fix: https://github.com/manyrandomthings/minitweaks/suites/2073841179/artifacts/41955508
