### ISSUE TITLE
[Suggestion] Make Jukebox output a redstone signal when playing music

### ISSUE THREAD

**Issue by felix91gr** [manyrandomthings/minitweaks#7]
Hi! Here's my suggestion. I tried to leave all of my thoughts here, I'd like to know what you think! ^^

Use case: currently, there's no way to detect if a jukebox is actively playing a song. With this, you could have disco lights and/or automatic music disk playlists!

Lemme explain: with carpet-extra, a dispenser can put and play disks into jukeboxes. This is great, because it has let us have disks we like start playing as soon as we step onto a special pressure plate, in our storage system. 
However, if we activated that pressure plate again, it would interrupt the playback and change the disk. So we reached a compromise and hardcoded a timer that keeps the dispenser blocked until 5 minutes have passed. This works, but it is a compromise. The dispenser stays blocked even if the jukebox has finished playing its song.
If we could somehow detect whether a jukebox was actively playing a song, we could make using it with redstone a lot more fun :3

Precedents:
- Carpet allowing dispensers to use music disks on jukeboxes
- Bedrock edition having jukeboxes output a signal when they are actively playing music

**Comment by manyrandomthings** [comment]
This would be nice but it's not possible to detect when a disc is playing because it's all client side. Having a signal stay on for a hardcoded amount of time wouldn't work either since the songs could be changed with resource packs
