### ISSUE TITLE
1.17 to 1.16 Shulker cloning issues

### ISSUE THREAD

**Issue by Scorpion34** [manyrandomthings/minitweaks#8]
The shulker is supposed to he hit with the bullet and then make a clone and teleport away however, using Scicraft's design I've encountered an issue where the shulker teleports but does not clone itself was wondering if this could be potentially patched or given an option to make it how reliable shulker cloning is like 25%, 50%, 75 and so on or if the shulker cloning itself could be looked at because the beginning of Scicraft's farm is great it works like a charm but then for unknown reasons the shulker just doesn't get cloned that's about the general gist of my issue which I'm unaware on how to fix.

**Comment by manyrandomthings** [comment]
This rule is intended to be a direct copy of the mechanic from 1.17, so if what you're trying to do isn't working with this mod it won't work in 1.17. Shulkers will teleport but not clone if there's too many nearby shulkers, or if its health is too low.
I tested this rule out with the scicraft design and it was working. But there's also this design by cubicmetre that makes the scicraft design more reliable, if that's what you're looking for: https://youtu.be/Tv7uVHM43Bw
